### ISSUE TITLE
Окно ввода вопроса обрезается, когда становится активным

### ISSUE THREAD

**Issue by vyacheslav-lebedenko** [vyacheslav-lebedenko/http-qards.eu#9]
- ставим курсор в окно ввода вопроса
  --- окно передвигается вниз и обрезаются кнопки

Нужно сделать чтобы окно не становилось больше по размерам или посты опустить ниже

![2015-06-26_22-00-26](https://cloud.githubusercontent.com/assets/13032392/8385192/43590048-1c4f-11e5-8407-a1360e8aed35.png)

**Comment by AlexanderPlaksenko** [comment]
Project Closed
